name: build web app
on: push
jobs:
  build-project:
    name: build project
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: run cypress test
        uses: cypress-io/github-action@v2
        with:
          start: npm run e2e
